services:
  mysql:
    image: mysql:8.4
    container_name: is_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: integralservices
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      TZ: America/Santiago
    ports:
      - "3307:3306"   # host:container (3307 evita conflicto si ya tienes MySQL en 3306)
    volumes:
      - is_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uapp", "-papp"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: .
    container_name: is_backend
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    command: ["npm", "run", "dev"]

  worker:
    build: .
    container_name: is_worker
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    command: ["npm", "run", "dev:worker"]

volumes:
  is_mysql_data: